<?php

namespace Database\Seeders;

use App\Models\MasterKaryawan;
use Illuminate\Database\Seeder;

class MasterKaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $karyawan = [
            [
                'user_id' => 2,
                'nik' => '3312221908010005',
                'nama_lengkap' => 'Muhammad Aziiz Putra Nugroho',
                'nama_panggilan' => 'Aziiz',
                'gender' => 'L',
                'tempat_lahir' => 'Wonogiri',
                'tanggal_lahir' => '2001-08-19',
                'alamat' => 'Cabean, Bakung, RT 015 RW 007, Jogonalan, Klaten 57452',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'aziiz@xboss.asia',
                'no_telp' => '08563505050',
                'department_id' => 6,
                'jabatan_id' => 6,
                'tanggal_mulai_bekerja' => '2025-10-28',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 3,
                'nik' => '3674056807010004',
                'nama_lengkap' => 'Asiyah',
                'nama_panggilan' => 'Asiyah',
                'gender' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2001-07-28',
                'alamat' => 'Jl poncol indah 3 rt 02/02 no.75 cirendeu ciputat timur, Tanggerang Selatan, Banten',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'asiyah@xboss.id',
                'no_telp' => '081542389485',
                'department_id' => 1,
                'jabatan_id' => 1,
                'tanggal_mulai_bekerja' => '2025-10-28',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 4,
                'nik' => '3276031012910001',
                'nama_lengkap' => 'Fajar Rifaldi',
                'nama_panggilan' => 'Fajar',
                'gender' => 'L',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1991-12-10',
                'alamat' => 'Jl. Pendowo Gg. H. Mani No. 31 RT 007/009 Limo Depok',
                'agama' => 'Islam',
                'status_pernikahan' => 'Menikah',
                'email' => 'fajarrifaldi@xboss.id',
                'no_telp' => '087782206044',
                'department_id' => 5,
                'jabatan_id' => 6,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3674054104000001',
                'nama_lengkap' => 'Vinka Sabna Murya',
                'nama_panggilan' => 'Chika',
                'gender' => 'P',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2000-04-01',
                'alamat' => 'Jl Jambu Kp Utan RT 04/RW 05',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'vinka@xboss.id',
                'no_telp' => '089670088561',
                'department_id' => 4,
                'jabatan_id' => 5,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3174055207060001',
                'nama_lengkap' => 'Kaylla Laudya Pasha',
                'nama_panggilan' => 'Kaylla',
                'gender' => 'P',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2006-07-12',
                'alamat' => 'Jalan serua bulak Gang H. Nur ali Rt 04 Rw 019 Blok A',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'kaylla@xboss.id',
                'no_telp' => '087780968429',
                'department_id' => 7,
                'jabatan_id' => 7,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3201125304060005',
                'nama_lengkap' => 'Syahira Khairul Salwa',
                'nama_panggilan' => 'Rara',
                'gender' => 'P',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2006-04-13',
                'alamat' => 'Kab Bogor, Kec Kemang',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'rara@xboss.id',
                'no_telp' => '0895355332254',
                'department_id' => 7,
                'jabatan_id' => 7,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '1808081503020003',
                'nama_lengkap' => 'Heri Wahyudiono',
                'nama_panggilan' => 'Heri',
                'gender' => 'L',
                'tempat_lahir' => 'Way Kanan',
                'tanggal_lahir' => '2002-03-15',
                'alamat' => 'RT/RW: 001/001, Desa Way Tuba, Kec. Way Tuba Kab. Way Kanan, Lampung',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'heri@xboss.asia',
                'no_telp' => '081511065050',
                'department_id' => 3,
                'jabatan_id' => 3,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3276041002960002',
                'nama_lengkap' => 'Feirsha Puja Romadhona',
                'nama_panggilan' => 'Feirsha',
                'gender' => 'L',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1996-02-10',
                'alamat' => 'Jl. Taman Sari 1 Rt.007 Rw.003 Karang Tengah Lebak Bulus Jakarta Selatan',
                'agama' => 'Islam',
                'status_pernikahan' => 'Menikah',
                'email' => 'feirsha@xboss.id',
                'no_telp' => '0895380431796',
                'department_id' => 5,
                'jabatan_id' => 6,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3275096205070005',
                'nama_lengkap' => 'Calista Elysia Laoh',
                'nama_panggilan' => 'Calista',
                'gender' => 'P',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2007-05-22',
                'alamat' => 'Jl. Sulawesi eg27, Kel. Jatisari, Kec. Jatiasih, Kota Bekasi',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'calista@xboss.id',
                'no_telp' => '08978129734',
                'department_id' => 7,
                'jabatan_id' => 7,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3277032005960001',
                'nama_lengkap' => 'Galih Dwi Pratama',
                'nama_panggilan' => 'Galih',
                'gender' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1996-05-20',
                'alamat' => 'Komplek bukit cipageran indah blok cno 7 ( cimahi )',
                'agama' => 'Islam',
                'status_pernikahan' => 'Menikah',
                'email' => 'galih@xboss.id',
                'no_telp' => '085641824241',
                'department_id' => 5,
                'jabatan_id' => 6,
                'tanggal_mulai_bekerja' => '2025-10-28',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3216035003020006',
                'nama_lengkap' => 'Nurjanah As-syifa',
                'nama_panggilan' => 'Syifa',
                'gender' => 'P',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2003-03-10',
                'alamat' => 'Pondok Kost Limun, Gang Haji Limun No 11, RT.2/Rw.2',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'syifa@xboss.id',
                'no_telp' => '085810185159',
                'department_id' => 7,
                'jabatan_id' => 7,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => null,
                'nik' => '3173051906030007',
                'nama_lengkap' => 'Rio Habibullah',
                'nama_panggilan' => 'Rio',
                'gender' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2003-06-19',
                'alamat' => 'Vila Rizki Ilhami 2 Cluster Mina Blok E/45 rt04/14 Pengasinan Sawangan',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'rio@xboss.id',
                'no_telp' => '081293846989',
                'department_id' => 8,
                'jabatan_id' => 8,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Duplicate entry removed - same person as entry with user_id: 5
            // [
            //     'user_id' => null,
            //     'nik' => '35132004030000032',
            //     'nama_lengkap' => 'Firos Malik Abdillah',
            //     'nama_panggilan' => 'Firos',
            //     'gender' => 'L',
            //     'tempat_lahir' => 'Probolinggo',
            //     'tanggal_lahir' => '2000-03-04',
            //     'alamat' => 'Perum Kertas Leces Indah A2/17 rt20/03 Banjarsawah Tegalsilawan',
            //     'agama' => 'Islam',
            //     'status_pernikahan' => 'Belum Menikah',
            //     'email' => 'firos@xboss.asia',
            //     'no_telp' => '085236446961',
            //     'department_id' => 3,
            //     'jabatan_id' => 3,
            //     'tanggal_mulai_bekerja' => '2025-10-27',
            //     'status_karyawan' => 'probation',
            //     'is_active' => true,
            //     'created_by' => 1,
            //     'updated_by' => 1,
            // ],
            [
                'user_id' => null,
                'nik' => '3204052405020007',
                'nama_lengkap' => 'Muhammad Genta Ath Tharriq',
                'nama_panggilan' => 'Genti',
                'gender' => 'L',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2002-05-24',
                'alamat' => 'Komp Bumi Harapan Blok CC 9 No.1 Rt04/11 Cibiru Hilir Cieleunyi',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'genta@xbos.asia',
                'no_telp' => '08979823351',
                'department_id' => 8,
                'jabatan_id' => 8,
                'tanggal_mulai_bekerja' => '2025-10-27',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'user_id' => 5,
                'nik' => '3513200403000002',
                'nama_lengkap' => 'Firos Malik Abdillah',
                'nama_panggilan' => 'Firos',
                'gender' => 'L',
                'tempat_lahir' => 'Probolinggo',
                'tanggal_lahir' => '2000-03-04',
                'alamat' => 'Perum Kertas Leces Indah block A2 no17 kec. Tegalsiwalan kab. Probolinggo',
                'agama' => 'Islam',
                'status_pernikahan' => 'Belum Menikah',
                'email' => 'Firosmalik.job@gmail.com',
                'no_telp' => '085236446961',
                'department_id' => 3,
                'jabatan_id' => 3,
                'tanggal_mulai_bekerja' => '2025-10-14',
                'status_karyawan' => 'probation',
                'is_active' => true,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        foreach ($karyawan as $kar) {
            MasterKaryawan::updateOrCreate(
                ['nik' => $kar['nik']],
                $kar
            );
        }

        $this->command->info('✓ Master Karyawan seeded successfully!');
        $this->command->info('  - Total karyawan: ' . count($karyawan));
    }
}
